import type { AuthUser, UserRole } from "@/features/auth/types";

export type AppShortcut = {
  key: string;
  title: string;
  tallyHint: string;
  description: string;
  href?: string;
  roles?: UserRole[];
  platformAdminOnly?: boolean;
  opensMenu?: boolean;
  section?: "tally" | "factory" | "accounting" | "admin";
  exactTally?: boolean;
};

const allFactoryRoles: UserRole[] = ["OWNER", "ADMIN", "FINANCE", "MANAGEMENT"];
const operationsRoles: UserRole[] = ["OWNER", "ADMIN", "MANAGEMENT"];
const financeRoles: UserRole[] = ["OWNER", "ADMIN", "FINANCE"];

export const appShortcuts: AppShortcut[] = [
  {
    key: "F1",
    title: "Shortcut Help",
    tallyHint: "Help",
    description: "Open Factory1 help and documentation.",
    href: "/docs",
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+M",
    title: "Gateway",
    tallyHint: "Gateway",
    description: "Return to Gateway of Factory1.",
    href: "/dashboard",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "F2",
    title: "Date / Period",
    tallyHint: "Date",
    description: "Focus the voucher date or accounting period on voucher screens.",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+F2",
    title: "Change Period",
    tallyHint: "Period",
    description: "Change report or accounting period.",
    href: "/accounting?workspace=OVERVIEW",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "F3",
    title: "Company",
    tallyHint: "Company",
    description: "Company selection shortcut. Factory1 currently uses the active login organization.",
    href: "/organization-settings?section=company",
    roles: ["OWNER", "ADMIN"],
    section: "tally",
    exactTally: true,
  },
  {
    key: "F4",
    title: "Contra Voucher",
    tallyHint: "Contra",
    description: "Open contra voucher entry.",
    href: "/accounting?voucher=CONTRA",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "F5",
    title: "Payment Voucher",
    tallyHint: "Payment",
    description: "Open payment voucher entry.",
    href: "/accounting?voucher=PAYMENT",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "F6",
    title: "Receipt Voucher",
    tallyHint: "Receipt",
    description: "Open receipt voucher entry.",
    href: "/accounting?voucher=RECEIPT",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "F7",
    title: "Journal Voucher",
    tallyHint: "Journal",
    description: "Open journal voucher entry.",
    href: "/accounting?voucher=JOURNAL",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "F8",
    title: "Sales Voucher",
    tallyHint: "Sales",
    description: "Open billing for sales voucher entry.",
    href: "/billing?type=SALES",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "F9",
    title: "Purchase Voucher",
    tallyHint: "Purchase",
    description: "Open billing for purchase voucher entry.",
    href: "/billing?type=PURCHASE",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "F10",
    title: "Other Vouchers",
    tallyHint: "Other Vouchers",
    description: "Open debit and credit note voucher entry.",
    href: "/accounting?voucher=DEBIT_NOTE",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+F8",
    title: "Credit Note",
    tallyHint: "Credit Note",
    description: "Open credit note voucher entry.",
    href: "/accounting?voucher=CREDIT_NOTE",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+F9",
    title: "Debit Note",
    tallyHint: "Debit Note",
    description: "Open debit note voucher entry.",
    href: "/accounting?voucher=DEBIT_NOTE",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+F4",
    title: "Purchase Order",
    tallyHint: "Purc Order",
    description: "Open purchase order flow.",
    href: "/billing?type=PURCHASE",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+F5",
    title: "Sales Order",
    tallyHint: "Sales Order",
    description: "Open sales order flow.",
    href: "/billing?type=SALES",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+F7",
    title: "Stock Journal",
    tallyHint: "Stock Jrnl",
    description: "Open stock movement journal.",
    href: "/inventory",
    roles: operationsRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+F8",
    title: "Delivery Note",
    tallyHint: "Del Note",
    description: "Open delivery note flow.",
    href: "/billing?type=SALES",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+F9",
    title: "Receipt Note",
    tallyHint: "Rcpt Note",
    description: "Open receipt note / GRN flow.",
    href: "/billing?type=PURCHASE",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+F10",
    title: "Physical Stock",
    tallyHint: "Phys Stock",
    description: "Open physical stock adjustment.",
    href: "/inventory",
    roles: operationsRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+F10",
    title: "Memorandum Voucher",
    tallyHint: "Memo",
    description: "Open memorandum voucher flow.",
    href: "/accounting?workspace=VOUCHERS",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+F4",
    title: "Payroll Voucher",
    tallyHint: "Payroll",
    description: "Open payroll voucher flow.",
    href: "/payroll",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+F5",
    title: "Payroll Attendance / Rejections Out",
    tallyHint: "Attendance",
    description: "Open attendance or rejections out flow.",
    href: "/attendance",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+F6",
    title: "Rejections In",
    tallyHint: "Reject In",
    description: "Open inventory rejections in flow.",
    href: "/inventory",
    roles: operationsRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "F11",
    title: "Features",
    tallyHint: "Features",
    description: "Tally-style features shortcut. Configure Factory1 features from settings.",
    href: "/organization-settings?section=features",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "F12",
    title: "Configure",
    tallyHint: "Configure",
    description: "Open company configuration.",
    href: "/organization-settings",
    roles: ["OWNER", "ADMIN"],
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+A",
    title: "Accept",
    tallyHint: "Accept",
    description: "Accept or save the current entry.",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+Q",
    title: "Quit Without Saving",
    tallyHint: "Quit",
    description: "Quit without saving.",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+N",
    title: "Calculator",
    tallyHint: "Calculator",
    description: "Open calculator context.",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+Enter",
    title: "Alter Master",
    tallyHint: "Alter",
    description: "Alter master from voucher.",
    href: "/accounting?workspace=MASTERS",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+K",
    title: "Create Company",
    tallyHint: "Create Co",
    description: "Create company / organization.",
    href: "/signup",
    roles: ["OWNER", "ADMIN"],
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+G",
    title: "Create / Alter Master",
    tallyHint: "Masters",
    description: "Create or alter masters.",
    href: "/accounting?workspace=MASTERS",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+C",
    title: "Create Master",
    tallyHint: "Create",
    description: "Create master on the fly.",
    href: "/accounting?workspace=MASTERS",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+D",
    title: "Delete",
    tallyHint: "Delete",
    description: "Delete voucher or master where allowed.",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+I",
    title: "Insert Voucher",
    tallyHint: "Insert",
    description: "Insert voucher.",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+2",
    title: "Duplicate Voucher",
    tallyHint: "Duplicate",
    description: "Duplicate voucher.",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+A",
    title: "Add Voucher",
    tallyHint: "Add",
    description: "Add voucher.",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+X",
    title: "Cancel Voucher",
    tallyHint: "Cancel",
    description: "Cancel voucher.",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+R",
    title: "Remove Line",
    tallyHint: "Remove",
    description: "Remove line.",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+E",
    title: "Export",
    tallyHint: "Export",
    description: "Export data or report.",
    href: "/import-export",
    roles: ["OWNER", "ADMIN"],
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+M",
    title: "Email",
    tallyHint: "E-Mail",
    description: "Email report.",
    href: "/import-export",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+P",
    title: "Print",
    tallyHint: "Print",
    description: "Print current report or voucher.",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+Y",
    title: "Data Management",
    tallyHint: "Data",
    description: "Backup, restore, split, rewrite and other data operations.",
    href: "/import-export",
    roles: ["OWNER", "ADMIN"],
    section: "tally",
    exactTally: true,
  },
  {
    key: "Alt+O",
    title: "Import Data",
    tallyHint: "Import",
    description: "Import data.",
    href: "/import-export",
    roles: ["OWNER", "ADMIN"],
    section: "tally",
    exactTally: true,
  },
  {
    key: "PageUp",
    title: "Previous Voucher",
    tallyHint: "Prev Vch",
    description: "Go to previous voucher.",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "PageDown",
    title: "Next Voucher",
    tallyHint: "Next Vch",
    description: "Go to next voucher.",
    roles: financeRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+PageUp",
    title: "Previous Report",
    tallyHint: "Prev Report",
    description: "Go to previous report.",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+PageDown",
    title: "Next Report",
    tallyHint: "Next Report",
    description: "Go to next report.",
    roles: allFactoryRoles,
    section: "tally",
    exactTally: true,
  },
  {
    key: "Ctrl+Shift+D",
    title: "Dashboard",
    tallyHint: "Dashboard",
    description: "Open the factory dashboard.",
    href: "/dashboard",
    roles: allFactoryRoles,
    section: "factory",
  },
  {
    key: "Ctrl+Shift+E",
    title: "Employees",
    tallyHint: "Employees",
    description: "Open employee masters and access setup.",
    href: "/employees",
    roles: operationsRoles,
    section: "factory",
  },
  {
    key: "Ctrl+Shift+A",
    title: "Attendance",
    tallyHint: "Attendance",
    description: "Open attendance registers and auto attendance setup.",
    href: "/attendance",
    roles: operationsRoles,
    section: "factory",
  },
  {
    key: "Ctrl+Shift+Y",
    title: "Payroll",
    tallyHint: "Payroll",
    description: "Open salary runs and payroll approvals.",
    href: "/payroll",
    roles: financeRoles,
    section: "factory",
  },
  {
    key: "Ctrl+Shift+I",
    title: "Inventory",
    tallyHint: "Inventory",
    description: "Open stock items, movement and low-stock controls.",
    href: "/inventory",
    roles: operationsRoles,
    section: "factory",
  },
  {
    key: "Ctrl+Shift+P",
    title: "Products / BOM",
    tallyHint: "Products",
    description: "Open products, BOM and production entries.",
    href: "/products",
    roles: operationsRoles,
    section: "factory",
  },
  {
    key: "Ctrl+Shift+S",
    title: "Suppliers",
    tallyHint: "Suppliers",
    description: "Open supplier masters.",
    href: "/suppliers",
    roles: operationsRoles,
    section: "factory",
  },
  {
    key: "Ctrl+Shift+C",
    title: "Customers",
    tallyHint: "Customers",
    description: "Open customer masters.",
    href: "/customers",
    roles: financeRoles,
    section: "factory",
  },
  {
    key: "Ctrl+Shift+B",
    title: "Billing",
    tallyHint: "Billing",
    description: "Open billing voucher entry.",
    href: "/billing",
    roles: financeRoles,
    section: "factory",
  },
  {
    key: "Ctrl+Shift+M",
    title: "Accounting Masters",
    tallyHint: "Masters",
    description: "Open account groups and ledgers.",
    href: "/accounting?workspace=MASTERS",
    roles: financeRoles,
    section: "accounting",
  },
  {
    key: "Ctrl+Shift+V",
    title: "Accounting Vouchers",
    tallyHint: "Vouchers",
    description: "Open accounting voucher entry.",
    href: "/accounting?workspace=VOUCHERS",
    roles: financeRoles,
    section: "accounting",
  },
  {
    key: "Ctrl+Shift+K",
    title: "Cash / Bank",
    tallyHint: "Cash/Bank",
    description: "Open cash and bank book.",
    href: "/accounting?workspace=CASH_BANK",
    roles: financeRoles,
    section: "accounting",
  },
  {
    key: "Ctrl+Shift+T",
    title: "Taxes",
    tallyHint: "Taxes",
    description: "Open GST, TDS and TCS controls.",
    href: "/accounting?workspace=TAXES",
    roles: financeRoles,
    section: "accounting",
  },
  {
    key: "Ctrl+Shift+G",
    title: "GST Integration",
    tallyHint: "GST",
    description: "Open GST and e-way bill integration settings.",
    href: "/settings/gst-integration",
    roles: ["OWNER", "ADMIN", "FINANCE"],
    section: "factory",
  },
  {
    key: "Ctrl+Shift+X",
    title: "Import / Export",
    tallyHint: "Import/Export",
    description: "Open data job history.",
    href: "/import-export",
    roles: ["OWNER", "ADMIN"],
    section: "factory",
  },
  {
    key: "Ctrl+Shift+H",
    title: "AI Assistant",
    tallyHint: "AI",
    description: "Open Factory1 AI assistant.",
    href: "/ai",
    roles: allFactoryRoles,
    section: "factory",
  },
  {
    key: "Ctrl+Shift+L",
    title: "Documentation",
    tallyHint: "Docs",
    description: "Open module documentation.",
    href: "/docs",
    roles: allFactoryRoles,
    section: "factory",
  },
  {
    key: "Ctrl+Shift+1",
    title: "SaaS Admin",
    tallyHint: "SaaS",
    description: "Open SaaS owner dashboard.",
    href: "/saas-admin",
    roles: ["SAAS_OWNER"],
    platformAdminOnly: true,
    section: "admin",
  },
  {
    key: "Ctrl+Shift+2",
    title: "Registered Factories",
    tallyHint: "Factories",
    description: "Open registered factories.",
    href: "/saas-admin/factories",
    roles: ["SAAS_OWNER"],
    platformAdminOnly: true,
    section: "admin",
  },
  {
    key: "Ctrl+Shift+3",
    title: "SaaS Insights",
    tallyHint: "Insights",
    description: "Open SaaS usage insights.",
    href: "/saas-admin/insights",
    roles: ["SAAS_OWNER"],
    platformAdminOnly: true,
    section: "admin",
  },
  {
    key: "Ctrl+Shift+4",
    title: "SaaS Marketing",
    tallyHint: "Marketing",
    description: "Open SaaS marketing controls.",
    href: "/saas-admin/marketing",
    roles: ["SAAS_OWNER"],
    platformAdminOnly: true,
    section: "admin",
  },
];

export function visibleShortcuts(user: AuthUser | null) {
  return appShortcuts.filter((shortcut) => canUseShortcut(shortcut, user));
}

export function canUseShortcut(
  shortcut: AppShortcut,
  user: AuthUser | null
) {
  if (shortcut.opensMenu) {
    return true;
  }

  if (shortcut.platformAdminOnly) {
    return Boolean(user?.platformAdmin);
  }

  if (user?.platformAdmin) {
    return false;
  }

  if (!shortcut.roles?.length) {
    return true;
  }

  return Boolean(user?.role && shortcut.roles.includes(user.role));
}

export const openShortcutsMenuEvent = "factory1:open-shortcuts";
